# Global clock & reset
set_property PACKAGE_PIN A30 [get_ports {sys_rst_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {sys_rst_n}]

set_property PACKAGE_PIN J28 [get_ports {sys_clk100m_p}]
set_property IOSTANDARD LVDS [get_ports {sys_clk100m_p}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {sys_clk100m_p}]
set_property PACKAGE_PIN J29 [get_ports {sys_clk100m_n}]

create_clock -period 10.000 -name sys_clk100m [get_ports sys_clk100m_p]

# DDR4 SODIMM
set_property PACKAGE_PIN J20 [get_ports {ddr4_refclk_clk_p}]
set_property IOSTANDARD LVDS [get_ports {ddr4_refclk_clk_p}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ddr4_refclk_clk_p}]
set_property PACKAGE_PIN J19 [get_ports {ddr4_refclk_clk_n}]

create_clock -period 10.631 -name ddr4_refclk [get_ports ddr4_refclk_clk_p]

set_property PACKAGE_PIN J18 [get_ports {ddr4_act_n}]
set_property PACKAGE_PIN K21 [get_ports {ddr4_adr[0]}]
set_property PACKAGE_PIN A20 [get_ports {ddr4_adr[1]}]
set_property PACKAGE_PIN D21 [get_ports {ddr4_adr[2]}]
set_property PACKAGE_PIN D20 [get_ports {ddr4_adr[3]}]
set_property PACKAGE_PIN L20 [get_ports {ddr4_adr[4]}]
set_property PACKAGE_PIN K20 [get_ports {ddr4_adr[5]}]
set_property PACKAGE_PIN B19 [get_ports {ddr4_adr[6]}]
set_property PACKAGE_PIN L19 [get_ports {ddr4_adr[7]}]
set_property PACKAGE_PIN A19 [get_ports {ddr4_adr[8]}]
set_property PACKAGE_PIN C19 [get_ports {ddr4_adr[9]}]
set_property PACKAGE_PIN E20 [get_ports {ddr4_adr[10]}]
set_property PACKAGE_PIN K18 [get_ports {ddr4_adr[11]}]
set_property PACKAGE_PIN D19 [get_ports {ddr4_adr[12]}]
set_property PACKAGE_PIN G21 [get_ports {ddr4_adr[13]}]
set_property PACKAGE_PIN E18 [get_ports {ddr4_adr[14]}]
set_property PACKAGE_PIN E21 [get_ports {ddr4_adr[15]}]
set_property PACKAGE_PIN G20 [get_ports {ddr4_adr[16]}]
set_property PACKAGE_PIN F20 [get_ports {ddr4_ba[0]}]
set_property PACKAGE_PIN H19 [get_ports {ddr4_ba[1]}]
set_property PACKAGE_PIN A18 [get_ports {ddr4_bg[0]}]
set_property PACKAGE_PIN C18 [get_ports {ddr4_bg[1]}]
set_property PACKAGE_PIN B21 [get_ports {ddr4_ck_c[0]}]
set_property PACKAGE_PIN C21 [get_ports {ddr4_ck_t[0]}]
set_property PACKAGE_PIN H21 [get_ports {ddr4_ck_c[1]}]
set_property PACKAGE_PIN J21 [get_ports {ddr4_ck_t[1]}]
set_property PACKAGE_PIN D18 [get_ports {ddr4_cke[0]}]
set_property PACKAGE_PIN K17 [get_ports {ddr4_cke[1]}]
set_property PACKAGE_PIN F18 [get_ports {ddr4_cs_n[0]}]
set_property PACKAGE_PIN F19 [get_ports {ddr4_cs_n[1]}]
set_property PACKAGE_PIN D13 [get_ports {ddr4_dm_n[0]}]
set_property PACKAGE_PIN G14 [get_ports {ddr4_dm_n[1]}]
set_property PACKAGE_PIN L13 [get_ports {ddr4_dm_n[2]}]
set_property PACKAGE_PIN P13 [get_ports {ddr4_dm_n[3]}]
set_property PACKAGE_PIN R21 [get_ports {ddr4_dm_n[4]}]
set_property PACKAGE_PIN L25 [get_ports {ddr4_dm_n[5]}]
set_property PACKAGE_PIN G25 [get_ports {ddr4_dm_n[6]}]
set_property PACKAGE_PIN C22 [get_ports {ddr4_dm_n[7]}]
set_property PACKAGE_PIN A13 [get_ports {ddr4_dq[0]}]
set_property PACKAGE_PIN B16 [get_ports {ddr4_dq[1]}]
set_property PACKAGE_PIN A14 [get_ports {ddr4_dq[2]}]
set_property PACKAGE_PIN A17 [get_ports {ddr4_dq[3]}]
set_property PACKAGE_PIN C14 [get_ports {ddr4_dq[4]}]
set_property PACKAGE_PIN C16 [get_ports {ddr4_dq[5]}]
set_property PACKAGE_PIN B14 [get_ports {ddr4_dq[6]}]
set_property PACKAGE_PIN B17 [get_ports {ddr4_dq[7]}]
set_property PACKAGE_PIN G15 [get_ports {ddr4_dq[8]}]
set_property PACKAGE_PIN F13 [get_ports {ddr4_dq[9]}]
set_property PACKAGE_PIN E15 [get_ports {ddr4_dq[10]}]
set_property PACKAGE_PIN D16 [get_ports {ddr4_dq[11]}]
set_property PACKAGE_PIN D15 [get_ports {ddr4_dq[12]}]
set_property PACKAGE_PIN E13 [get_ports {ddr4_dq[13]}]
set_property PACKAGE_PIN E16 [get_ports {ddr4_dq[14]}]
set_property PACKAGE_PIN F15 [get_ports {ddr4_dq[15]}]
set_property PACKAGE_PIN J13 [get_ports {ddr4_dq[16]}]
set_property PACKAGE_PIN K15 [get_ports {ddr4_dq[17]}]
set_property PACKAGE_PIN J14 [get_ports {ddr4_dq[18]}]
set_property PACKAGE_PIN K16 [get_ports {ddr4_dq[19]}]
set_property PACKAGE_PIN H13 [get_ports {ddr4_dq[20]}]
set_property PACKAGE_PIN J15 [get_ports {ddr4_dq[21]}]
set_property PACKAGE_PIN H14 [get_ports {ddr4_dq[22]}]
set_property PACKAGE_PIN J16 [get_ports {ddr4_dq[23]}]
set_property PACKAGE_PIN L14 [get_ports {ddr4_dq[24]}]
set_property PACKAGE_PIN N14 [get_ports {ddr4_dq[25]}]
set_property PACKAGE_PIN P15 [get_ports {ddr4_dq[26]}]
set_property PACKAGE_PIN N16 [get_ports {ddr4_dq[27]}]
set_property PACKAGE_PIN M14 [get_ports {ddr4_dq[28]}]
set_property PACKAGE_PIN P14 [get_ports {ddr4_dq[29]}]
set_property PACKAGE_PIN R15 [get_ports {ddr4_dq[30]}]
set_property PACKAGE_PIN M16 [get_ports {ddr4_dq[31]}]
set_property PACKAGE_PIN N22 [get_ports {ddr4_dq[32]}]
set_property PACKAGE_PIN P23 [get_ports {ddr4_dq[33]}]
set_property PACKAGE_PIN R25 [get_ports {ddr4_dq[34]}]
set_property PACKAGE_PIN M25 [get_ports {ddr4_dq[35]}]
set_property PACKAGE_PIN M22 [get_ports {ddr4_dq[36]}]
set_property PACKAGE_PIN N23 [get_ports {ddr4_dq[37]}]
set_property PACKAGE_PIN P25 [get_ports {ddr4_dq[38]}]
set_property PACKAGE_PIN M24 [get_ports {ddr4_dq[39]}]
set_property PACKAGE_PIN L23 [get_ports {ddr4_dq[40]}]
set_property PACKAGE_PIN K23 [get_ports {ddr4_dq[41]}]
set_property PACKAGE_PIN H24 [get_ports {ddr4_dq[42]}]
set_property PACKAGE_PIN J23 [get_ports {ddr4_dq[43]}]
set_property PACKAGE_PIN K22 [get_ports {ddr4_dq[44]}]
set_property PACKAGE_PIN L22 [get_ports {ddr4_dq[45]}]
set_property PACKAGE_PIN J24 [get_ports {ddr4_dq[46]}]
set_property PACKAGE_PIN H23 [get_ports {ddr4_dq[47]}]
set_property PACKAGE_PIN F24 [get_ports {ddr4_dq[48]}]
set_property PACKAGE_PIN D23 [get_ports {ddr4_dq[49]}]
set_property PACKAGE_PIN E25 [get_ports {ddr4_dq[50]}]
set_property PACKAGE_PIN D24 [get_ports {ddr4_dq[51]}]
set_property PACKAGE_PIN F22 [get_ports {ddr4_dq[52]}]
set_property PACKAGE_PIN F23 [get_ports {ddr4_dq[53]}]
set_property PACKAGE_PIN D25 [get_ports {ddr4_dq[54]}]
set_property PACKAGE_PIN G22 [get_ports {ddr4_dq[55]}]
set_property PACKAGE_PIN C24 [get_ports {ddr4_dq[56]}]
set_property PACKAGE_PIN A24 [get_ports {ddr4_dq[57]}]
set_property PACKAGE_PIN B26 [get_ports {ddr4_dq[58]}]
set_property PACKAGE_PIN C26 [get_ports {ddr4_dq[59]}]
set_property PACKAGE_PIN B24 [get_ports {ddr4_dq[60]}]
set_property PACKAGE_PIN C23 [get_ports {ddr4_dq[61]}]
set_property PACKAGE_PIN B25 [get_ports {ddr4_dq[62]}]
set_property PACKAGE_PIN A25 [get_ports {ddr4_dq[63]}]
set_property PACKAGE_PIN A15 [get_ports {ddr4_dqs_c[0]}]
set_property PACKAGE_PIN B15 [get_ports {ddr4_dqs_t[0]}]
set_property PACKAGE_PIN G16 [get_ports {ddr4_dqs_c[1]}]
set_property PACKAGE_PIN G17 [get_ports {ddr4_dqs_t[1]}]
set_property PACKAGE_PIN H16 [get_ports {ddr4_dqs_c[2]}]
set_property PACKAGE_PIN H17 [get_ports {ddr4_dqs_t[2]}]
set_property PACKAGE_PIN P16 [get_ports {ddr4_dqs_c[3]}]
set_property PACKAGE_PIN R16 [get_ports {ddr4_dqs_t[3]}]
set_property PACKAGE_PIN N24 [get_ports {ddr4_dqs_c[4]}]
set_property PACKAGE_PIN P24 [get_ports {ddr4_dqs_t[4]}]
set_property PACKAGE_PIN J25 [get_ports {ddr4_dqs_c[5]}]
set_property PACKAGE_PIN K25 [get_ports {ddr4_dqs_t[5]}]
set_property PACKAGE_PIN E22 [get_ports {ddr4_dqs_c[6]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_dqs_t[6]}]
set_property PACKAGE_PIN A22 [get_ports {ddr4_dqs_c[7]}]
set_property PACKAGE_PIN A23 [get_ports {ddr4_dqs_t[7]}]
set_property PACKAGE_PIN G19 [get_ports {ddr4_odt[0]}]
set_property PACKAGE_PIN H18 [get_ports {ddr4_odt[1]}]
set_property PACKAGE_PIN B20 [get_ports {ddr4_parity}]
set_property PACKAGE_PIN L18 [get_ports {ddr4_reset_n}]

# # FMC0 LPC
# set_property PACKAGE_PIN AP14 [get_ports {fmc0_clk0_c2m_n}]
# set_property PACKAGE_PIN AP15 [get_ports {fmc0_clk0_c2m_p}]
# set_property PACKAGE_PIN AW13 [get_ports {fmc0_clk0_m2c_n}]
# set_property PACKAGE_PIN AW14 [get_ports {fmc0_clk0_m2c_p}]
# set_property PACKAGE_PIN AE8  [get_ports {fmc0_dp0_c2m_n}]
# set_property PACKAGE_PIN AE9  [get_ports {fmc0_dp0_c2m_p}]
# set_property PACKAGE_PIN AE3  [get_ports {fmc0_dp0_m2c_n}]
# set_property PACKAGE_PIN AE4  [get_ports {fmc0_dp0_m2c_p}]
# set_property PACKAGE_PIN AD10 [get_ports {fmc0_gbtclk0_n}]
# set_property PACKAGE_PIN AD11 [get_ports {fmc0_gbtclk0_p}]
# set_property PACKAGE_PIN BB7  [get_ports {fmc0_la00_cc_n}]
# set_property PACKAGE_PIN BA7  [get_ports {fmc0_la00_cc_p}]
# set_property PACKAGE_PIN AR13 [get_ports {fmc0_la01_cc_n}]
# set_property PACKAGE_PIN AP13 [get_ports {fmc0_la01_cc_p}]
# set_property PACKAGE_PIN BF7  [get_ports {fmc0_la02_n}]
# set_property PACKAGE_PIN BE7  [get_ports {fmc0_la02_p}]
# set_property PACKAGE_PIN BC7  [get_ports {fmc0_la03_n}]
# set_property PACKAGE_PIN BC8  [get_ports {fmc0_la03_p}]
# set_property PACKAGE_PIN BF8  [get_ports {fmc0_la04_n}]
# set_property PACKAGE_PIN BE8  [get_ports {fmc0_la04_p}]
# set_property PACKAGE_PIN AY11 [get_ports {fmc0_la05_n}]
# set_property PACKAGE_PIN AY12 [get_ports {fmc0_la05_p}]
# set_property PACKAGE_PIN AN13 [get_ports {fmc0_la06_n}]
# set_property PACKAGE_PIN AN14 [get_ports {fmc0_la06_p}]
# set_property PACKAGE_PIN BD8  [get_ports {fmc0_la07_n}]
# set_property PACKAGE_PIN BD9  [get_ports {fmc0_la07_p}]
# set_property PACKAGE_PIN BA8  [get_ports {fmc0_la08_n}]
# set_property PACKAGE_PIN BA9  [get_ports {fmc0_la08_p}]
# set_property PACKAGE_PIN BA13 [get_ports {fmc0_la09_n}]
# set_property PACKAGE_PIN AY13 [get_ports {fmc0_la09_p}]
# set_property PACKAGE_PIN AV13 [get_ports {fmc0_la10_n}]
# set_property PACKAGE_PIN AU13 [get_ports {fmc0_la10_p}]
# set_property PACKAGE_PIN BF9  [get_ports {fmc0_la11_n}]
# set_property PACKAGE_PIN BF10 [get_ports {fmc0_la11_p}]
# set_property PACKAGE_PIN BC9  [get_ports {fmc0_la12_n}]
# set_property PACKAGE_PIN BB9  [get_ports {fmc0_la12_p}]
# set_property PACKAGE_PIN AM14 [get_ports {fmc0_la13_n}]
# set_property PACKAGE_PIN AL14 [get_ports {fmc0_la13_p}]
# set_property PACKAGE_PIN AM15 [get_ports {fmc0_la14_n}]
# set_property PACKAGE_PIN AL15 [get_ports {fmc0_la14_p}]
# set_property PACKAGE_PIN BE10 [get_ports {fmc0_la15_n}]
# set_property PACKAGE_PIN BE11 [get_ports {fmc0_la15_p}]
# set_property PACKAGE_PIN BB10 [get_ports {fmc0_la16_n}]
# set_property PACKAGE_PIN BB11 [get_ports {fmc0_la16_p}]
# set_property PACKAGE_PIN AV14 [get_ports {fmc0_la17_cc_n}]
# set_property PACKAGE_PIN AU14 [get_ports {fmc0_la17_cc_p}]
# set_property PACKAGE_PIN AR15 [get_ports {fmc0_la18_cc_n}]
# set_property PACKAGE_PIN AR16 [get_ports {fmc0_la18_cc_p}]
# set_property PACKAGE_PIN BF12 [get_ports {fmc0_la19_n}]
# set_property PACKAGE_PIN BE12 [get_ports {fmc0_la19_p}]
# set_property PACKAGE_PIN BC11 [get_ports {fmc0_la20_n}]
# set_property PACKAGE_PIN BC12 [get_ports {fmc0_la20_p}]
# set_property PACKAGE_PIN BE13 [get_ports {fmc0_la21_n}]
# set_property PACKAGE_PIN BD13 [get_ports {fmc0_la21_p}]
# set_property PACKAGE_PIN BB12 [get_ports {fmc0_la22_n}]
# set_property PACKAGE_PIN BA12 [get_ports {fmc0_la22_p}]
# set_property PACKAGE_PIN AW15 [get_ports {fmc0_la23_n}]
# set_property PACKAGE_PIN AW16 [get_ports {fmc0_la23_p}]
# set_property PACKAGE_PIN BF13 [get_ports {fmc0_la24_n}]
# set_property PACKAGE_PIN BF14 [get_ports {fmc0_la24_p}]
# set_property PACKAGE_PIN BC13 [get_ports {fmc0_la25_n}]
# set_property PACKAGE_PIN BC14 [get_ports {fmc0_la25_p}]
# set_property PACKAGE_PIN AU15 [get_ports {fmc0_la26_n}]
# set_property PACKAGE_PIN AT15 [get_ports {fmc0_la26_p}]
# set_property PACKAGE_PIN AV16 [get_ports {fmc0_la27_n}]
# set_property PACKAGE_PIN AU16 [get_ports {fmc0_la27_p}]
# set_property PACKAGE_PIN BD14 [get_ports {fmc0_la28_n}]
# set_property PACKAGE_PIN BD15 [get_ports {fmc0_la28_p}]
# set_property PACKAGE_PIN BB14 [get_ports {fmc0_la29_n}]
# set_property PACKAGE_PIN BB15 [get_ports {fmc0_la29_p}]
# set_property PACKAGE_PIN BF15 [get_ports {fmc0_la30_n}]
# set_property PACKAGE_PIN BE15 [get_ports {fmc0_la30_p}]
# set_property PACKAGE_PIN BA14 [get_ports {fmc0_la31_n}]
# set_property PACKAGE_PIN BA15 [get_ports {fmc0_la31_p}]
# set_property PACKAGE_PIN BE16 [get_ports {fmc0_la32_n}]
# set_property PACKAGE_PIN BD16 [get_ports {fmc0_la32_p}]
# set_property PACKAGE_PIN AY15 [get_ports {fmc0_la33_n}]
# set_property PACKAGE_PIN AY16 [get_ports {fmc0_la33_p}]

# mikroBUS
set_property -dict {PACKAGE_PIN C28  IOSTANDARD LVCMOS18} [get_ports {mbus_an}]
set_property -dict {PACKAGE_PIN F27  IOSTANDARD LVCMOS18} [get_ports {mbus_int}]
set_property -dict {PACKAGE_PIN E28  IOSTANDARD LVCMOS18} [get_ports {mbus_cs}]
set_property -dict {PACKAGE_PIN D29  IOSTANDARD LVCMOS18} [get_ports {mbus_miso}]
set_property -dict {PACKAGE_PIN F29  IOSTANDARD LVCMOS18} [get_ports {mbus_mosi}]
set_property -dict {PACKAGE_PIN C29  IOSTANDARD LVCMOS18} [get_ports {mbus_sck}]
set_property -dict {PACKAGE_PIN E26  IOSTANDARD LVCMOS18} [get_ports {mbus_rx}]
set_property -dict {PACKAGE_PIN H29  IOSTANDARD LVCMOS18} [get_ports {mbus_tx}]
set_property -dict {PACKAGE_PIN G29  IOSTANDARD LVCMOS18} [get_ports {mbus_scl}]
set_property -dict {PACKAGE_PIN H28  IOSTANDARD LVCMOS18} [get_ports {mbus_sda}]
set_property -dict {PACKAGE_PIN E27  IOSTANDARD LVCMOS18} [get_ports {mbus_pwm}]
set_property -dict {PACKAGE_PIN D28  IOSTANDARD LVCMOS18} [get_ports {mbus_rst}]

# UART to MCU (crossover-ed)
set_property -dict {PACKAGE_PIN E30  IOSTANDARD LVCMOS18} [get_ports {mcu_uart_txd}]
set_property -dict {PACKAGE_PIN D30  IOSTANDARD LVCMOS18} [get_ports {mcu_uart_rxd}]

# PCIe
set_property PACKAGE_PIN AT11 [get_ports {pcie_clk100m_p}]
set_property IOSTANDARD LVDS [get_ports {pcie_clk100m_p}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {pcie_clk100m_p}]
set_property PACKAGE_PIN AT10 [get_ports {pcie_clk100m_n}]

create_clock -period 10.000 -name pcie_clk100m [get_ports pcie_clk100m_p]

set_property PACKAGE_PIN AR26 [get_ports {pcie_perstn}]
set_property IOSTANDARD LVCMOS18 [get_ports {pcie_perstn}]

set_property PACKAGE_PIN AF6  [get_ports {pcie_mgt_txn[0]}]
set_property PACKAGE_PIN AF7  [get_ports {pcie_mgt_txp[0]}]
set_property PACKAGE_PIN AG8  [get_ports {pcie_mgt_txn[1]}]
set_property PACKAGE_PIN AG9  [get_ports {pcie_mgt_txp[1]}]
set_property PACKAGE_PIN AT6  [get_ports {pcie_mgt_txn[10]}]
set_property PACKAGE_PIN AT7  [get_ports {pcie_mgt_txp[10]}]
set_property PACKAGE_PIN AU8  [get_ports {pcie_mgt_txn[11]}]
set_property PACKAGE_PIN AU9  [get_ports {pcie_mgt_txp[11]}]
set_property PACKAGE_PIN AV6  [get_ports {pcie_mgt_txn[12]}]
set_property PACKAGE_PIN AV7  [get_ports {pcie_mgt_txp[12]}]
set_property PACKAGE_PIN BB4  [get_ports {pcie_mgt_txn[13]}]
set_property PACKAGE_PIN BB5  [get_ports {pcie_mgt_txp[13]}]
set_property PACKAGE_PIN BD4  [get_ports {pcie_mgt_txn[14]}]
set_property PACKAGE_PIN BD5  [get_ports {pcie_mgt_txp[14]}]
set_property PACKAGE_PIN BF4  [get_ports {pcie_mgt_txn[15]}]
set_property PACKAGE_PIN BF5  [get_ports {pcie_mgt_txp[15]}]
set_property PACKAGE_PIN AH6  [get_ports {pcie_mgt_txn[2]}]
set_property PACKAGE_PIN AH7  [get_ports {pcie_mgt_txp[2]}]
set_property PACKAGE_PIN AJ8  [get_ports {pcie_mgt_txn[3]}]
set_property PACKAGE_PIN AJ9  [get_ports {pcie_mgt_txp[3]}]
set_property PACKAGE_PIN AK6  [get_ports {pcie_mgt_txn[4]}]
set_property PACKAGE_PIN AK7  [get_ports {pcie_mgt_txp[4]}]
set_property PACKAGE_PIN AL8  [get_ports {pcie_mgt_txn[5]}]
set_property PACKAGE_PIN AL9  [get_ports {pcie_mgt_txp[5]}]
set_property PACKAGE_PIN AM6  [get_ports {pcie_mgt_txn[6]}]
set_property PACKAGE_PIN AM7  [get_ports {pcie_mgt_txp[6]}]
set_property PACKAGE_PIN AN8  [get_ports {pcie_mgt_txn[7]}]
set_property PACKAGE_PIN AN9  [get_ports {pcie_mgt_txp[7]}]
set_property PACKAGE_PIN AP6  [get_ports {pcie_mgt_txn[8]}]
set_property PACKAGE_PIN AP7  [get_ports {pcie_mgt_txp[8]}]
set_property PACKAGE_PIN AR8  [get_ports {pcie_mgt_txn[9]}]
set_property PACKAGE_PIN AR9  [get_ports {pcie_mgt_txp[9]}]
set_property PACKAGE_PIN AF1  [get_ports {pcie_mgt_rxn[0]}]
set_property PACKAGE_PIN AF2  [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN AG3  [get_ports {pcie_mgt_rxn[1]}]
set_property PACKAGE_PIN AG4  [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN AT1  [get_ports {pcie_mgt_rxn[10]}]
set_property PACKAGE_PIN AT2  [get_ports {pcie_mgt_rxp[10]}]
set_property PACKAGE_PIN AU3  [get_ports {pcie_mgt_rxn[11]}]
set_property PACKAGE_PIN AU4  [get_ports {pcie_mgt_rxp[11]}]
set_property PACKAGE_PIN AV1  [get_ports {pcie_mgt_rxn[12]}]
set_property PACKAGE_PIN AV2  [get_ports {pcie_mgt_rxp[12]}]
set_property PACKAGE_PIN AW3  [get_ports {pcie_mgt_rxn[13]}]
set_property PACKAGE_PIN AW4  [get_ports {pcie_mgt_rxp[13]}]
set_property PACKAGE_PIN BA1  [get_ports {pcie_mgt_rxn[14]}]
set_property PACKAGE_PIN BA2  [get_ports {pcie_mgt_rxp[14]}]
set_property PACKAGE_PIN BC1  [get_ports {pcie_mgt_rxn[15]}]
set_property PACKAGE_PIN BC2  [get_ports {pcie_mgt_rxp[15]}]
set_property PACKAGE_PIN AH1  [get_ports {pcie_mgt_rxn[2]}]
set_property PACKAGE_PIN AH2  [get_ports {pcie_mgt_rxp[2]}]
set_property PACKAGE_PIN AJ3  [get_ports {pcie_mgt_rxn[3]}]
set_property PACKAGE_PIN AJ4  [get_ports {pcie_mgt_rxp[3]}]
set_property PACKAGE_PIN AK1  [get_ports {pcie_mgt_rxn[4]}]
set_property PACKAGE_PIN AK2  [get_ports {pcie_mgt_rxp[4]}]
set_property PACKAGE_PIN AL3  [get_ports {pcie_mgt_rxn[5]}]
set_property PACKAGE_PIN AL4  [get_ports {pcie_mgt_rxp[5]}]
set_property PACKAGE_PIN AM1  [get_ports {pcie_mgt_rxn[6]}]
set_property PACKAGE_PIN AM2  [get_ports {pcie_mgt_rxp[6]}]
set_property PACKAGE_PIN AN3  [get_ports {pcie_mgt_rxn[7]}]
set_property PACKAGE_PIN AN4  [get_ports {pcie_mgt_rxp[7]}]
set_property PACKAGE_PIN AP1  [get_ports {pcie_mgt_rxn[8]}]
set_property PACKAGE_PIN AP2  [get_ports {pcie_mgt_rxp[8]}]
set_property PACKAGE_PIN AR3  [get_ports {pcie_mgt_rxn[9]}]
set_property PACKAGE_PIN AR4  [get_ports {pcie_mgt_rxp[9]}]
set_property PACKAGE_PIN AP10 [get_ports {pcie_refclk_clk_n}]
set_property PACKAGE_PIN AP11 [get_ports {pcie_refclk_clk_p}]

# QSFP0
set_property PACKAGE_PIN H27 [get_ports {qsfp0_modprs}]
set_property PACKAGE_PIN F28 [get_ports {qsfp0_rxlos}]
set_property PACKAGE_PIN G27 [get_ports {qsfp0_scl}]
set_property PACKAGE_PIN K27 [get_ports {qsfp0_sda}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp0_modprs}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp0_rxlos}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp0_scl}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp0_sda}]

set_property PACKAGE_PIN B10  [get_ports {qsfp0_refclk_n}]
set_property PACKAGE_PIN B11  [get_ports {qsfp0_refclk_p}]
set_property PACKAGE_PIN D1   [get_ports {qsfp0_mgt_rxn[0]}]
set_property PACKAGE_PIN D2   [get_ports {qsfp0_mgt_rxp[0]}]
set_property PACKAGE_PIN E3   [get_ports {qsfp0_mgt_rxn[1]}]
set_property PACKAGE_PIN E4   [get_ports {qsfp0_mgt_rxp[1]}]
set_property PACKAGE_PIN A4   [get_ports {qsfp0_mgt_rxn[2]}]
set_property PACKAGE_PIN A5   [get_ports {qsfp0_mgt_rxp[2]}]
set_property PACKAGE_PIN C3   [get_ports {qsfp0_mgt_rxn[3]}]
set_property PACKAGE_PIN C4   [get_ports {qsfp0_mgt_rxp[3]}]
set_property PACKAGE_PIN D6   [get_ports {qsfp0_mgt_txn[0]}]
set_property PACKAGE_PIN D7   [get_ports {qsfp0_mgt_txp[0]}]
set_property PACKAGE_PIN E8   [get_ports {qsfp0_mgt_txn[1]}]
set_property PACKAGE_PIN E9   [get_ports {qsfp0_mgt_txp[1]}]
set_property PACKAGE_PIN A8   [get_ports {qsfp0_mgt_txn[2]}]
set_property PACKAGE_PIN A9   [get_ports {qsfp0_mgt_txp[2]}]
set_property PACKAGE_PIN C8   [get_ports {qsfp0_mgt_txn[3]}]
set_property PACKAGE_PIN C9   [get_ports {qsfp0_mgt_txp[3]}]

# QSFP1
set_property PACKAGE_PIN K28 [get_ports {qsfp1_modprs}]
set_property PACKAGE_PIN L29 [get_ports {qsfp1_rxlos}]
set_property PACKAGE_PIN L28 [get_ports {qsfp1_scl}]
set_property PACKAGE_PIN L27 [get_ports {qsfp1_sda}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp1_modprs}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp1_rxlos}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp1_scl}]
set_property IOSTANDARD LVCMOS18 [get_ports {qsfp1_sda}]

set_property PACKAGE_PIN F10  [get_ports {qsfp1_refclk_n}]
set_property PACKAGE_PIN F11  [get_ports {qsfp1_refclk_p}]
set_property PACKAGE_PIN H1   [get_ports {qsfp1_mgt_rxn[0]}]
set_property PACKAGE_PIN H2   [get_ports {qsfp1_mgt_rxp[0]}]
set_property PACKAGE_PIN J3   [get_ports {qsfp1_mgt_rxn[1]}]
set_property PACKAGE_PIN J4   [get_ports {qsfp1_mgt_rxp[1]}]
set_property PACKAGE_PIN G3   [get_ports {qsfp1_mgt_rxn[2]}]
set_property PACKAGE_PIN G4   [get_ports {qsfp1_mgt_rxp[2]}]
set_property PACKAGE_PIN F1   [get_ports {qsfp1_mgt_rxn[3]}]
set_property PACKAGE_PIN F2   [get_ports {qsfp1_mgt_rxp[3]}]
set_property PACKAGE_PIN H6   [get_ports {qsfp1_mgt_txn[0]}]
set_property PACKAGE_PIN H7   [get_ports {qsfp1_mgt_txp[0]}]
set_property PACKAGE_PIN J8   [get_ports {qsfp1_mgt_txn[1]}]
set_property PACKAGE_PIN J9   [get_ports {qsfp1_mgt_txp[1]}]
set_property PACKAGE_PIN G8   [get_ports {qsfp1_mgt_txn[2]}]
set_property PACKAGE_PIN G9   [get_ports {qsfp1_mgt_txp[2]}]
set_property PACKAGE_PIN F6   [get_ports {qsfp1_mgt_txn[3]}]
set_property PACKAGE_PIN F7   [get_ports {qsfp1_mgt_txp[3]}]
